version: '3.8'

services:
  # Servicio de la Aplicaci칩n Web (PHP + Apache)
  app:
    build: .
    ports:
      - "8080:80" # La web se ver치 en localhost:8080
    environment:
      # Sobrescribimos la conexi칩n para que use el servicio 'database' de abajo
      - DATABASE_URL=mysql://root:root@database:3306/viajes_para_ti?serverVersion=8.0&charset=utf8mb4
    depends_on:
      - database
    volumes:
      - .:/var/www/html # Sincroniza tu c칩digo con el contenedor

  # Servicio de Base de Datos
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: viajes_para_ti
    ports:
      - "3307:3306" # Puerto externo 3307 para no chocar con tu XAMPP (3306)
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: